FROM ocaml/opam
RUN opam depext -u iocaml
ENV OPAMYES=1
RUN opam install -j 2 iocaml
RUN opam pin add dockerfile --dev
RUN opam source dockerfile --dir=/tmp/dockerfile
RUN mkdir -p /tmp/dockerfile/html/ocaml-dockerfile
WORKDIR /tmp/dockerfile
RUN opam pin add iocamljs-kernel --dev
RUN opam config exec -- jsoo_mktop -verbose -dont-export-unit gc -export-package dockerfile -export-package iocamljs-kernel -jsopt +weak.js -jsopt +dynlink.js -jsopt +toplevel.js -o dockerfile.byte
RUN cat *.cmis.js $(opam config var lib)/iocamljs-kernel/kernel.js > $(opam config var share)/iocamljs-kernel/profile/static/services/kernels/js/kernel.dockerfile.js
RUN opam config exec -- iocaml -v -js dockerfile /tmp/dockerfile/notebooks/ -create-static-site /tmp/dockerfile/html/ocaml-dockerfile -static-site-base-path "/ocaml-dockerfile"
WORKDIR /tmp/dockerfile/html
EXPOSE 8080
CMD opam config exec -- cohttp-server-lwt -p 8080 -v /tmp/dockerfile/html
